import { StyleSheet } from "react-native"
import { typeface } from "@/theme/tokens"
import { MIN_TOUCH_TARGET, spacing, type Tokens } from "@/theme/tokens"

export const makeStyles = (t: Tokens, isDark: boolean) => StyleSheet.create({
  frame: { flex: 1, minHeight: 0 },
  stepHeader: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingBottom: spacing.md },
  stepLabel: { ...typeface.semibold, flex: 1, color: t.text, fontSize: 13,},
  refreshButton: { width: MIN_TOUCH_TARGET, height: MIN_TOUCH_TARGET, alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: t.inputBdr, borderRadius: 12, backgroundColor: t.cardBg },
  refreshPressed: { opacity: 0.7 },
  refreshDisabled: { opacity: 0.5 },
  scroll: { flex: 1 },
  content: { gap: spacing.lg, paddingBottom: spacing.lg },
  heading: { ...typeface.bold, color: t.strong, fontSize: 22,},
  text: { ...typeface.regular, color: t.strong, fontSize: 15, lineHeight: 22, flexShrink: 1 },
  muted: { ...typeface.regular, color: t.text, fontSize: 14, lineHeight: 21 },
  card: { borderWidth: 1, borderColor: t.cardBdr, borderRadius: 8, padding: spacing.lg, gap: spacing.md, backgroundColor: t.cardBg },
  photos: { height: 112, borderRadius: 8, overflow: "hidden", position: "relative", backgroundColor: t.subBg, borderWidth: 1, borderColor: t.pillBdr },
  photoBackdrop: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, opacity: 0.6 },
  photo: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  photoCode: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: isDark ? "#1e40af" : "#bfdbfe" },
  photoCodeText: { ...typeface.extraBold, color: t.accent, fontSize: 40, lineHeight: 44, fontVariant: ["tabular-nums"] },
  photoCodeLong: { ...typeface.regular, fontSize: 28, lineHeight: 32 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  choice: { flexGrow: 1, flexBasis: 130, minHeight: MIN_TOUCH_TARGET, padding: spacing.md, gap: spacing.xs,
    borderWidth: 2, borderColor: t.cardBdr, borderRadius: 8, backgroundColor: t.cardBg },
  selected: { borderColor: t.accent, backgroundColor: t.editBtnBg },
  disabled: { opacity: 0.5 },
  row: { flexDirection: "row", alignItems: "center", gap: spacing.md, flexWrap: "wrap" },
  icon: { minWidth: MIN_TOUCH_TARGET, minHeight: MIN_TOUCH_TARGET, alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: t.inputBdr, borderRadius: 8 },
  quantity: { ...typeface.regular, minWidth: 40, textAlign: "center", color: t.strong, fontSize: 18 },
  actionBar: { paddingTop: spacing.xl },
  actionBarContent: { gap: spacing.sm },
  actionSummary: { gap: spacing.xs },
  actionTitle: { ...typeface.bold, color: t.strong, fontSize: 16, flexShrink: 1 },
  actionButtons: { gap: spacing.sm },
  group: { gap: spacing.md },
  groupHeading: { ...typeface.bold, color: t.strong, fontSize: 16,},
  badge: { ...typeface.bold, color: t.accent, fontSize: 13,},
  noneRow: { gap: spacing.xs, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: t.divider },
  noneName: { ...typeface.semibold, color: t.strong, fontSize: 16,},
})
