import { StyleSheet } from "react-native"
import { typeface } from "@/theme/tokens"
import { radii, spacing, type Tokens } from "@/theme/tokens"

export const makeStyles = (t: Tokens) => StyleSheet.create({
  frame: { flex: 1, minHeight: 0 },
  stepHeader: { gap: spacing.sm, paddingBottom: spacing.md },
  stepLabel: { ...typeface.semibold, color: t.text, fontSize: 13,},
  scroll: { flex: 1 },
  content: { gap: spacing.lg, paddingBottom: spacing.lg },
  heading: { ...typeface.bold, color: t.strong, fontSize: 22,},
  text: { ...typeface.regular, color: t.strong, fontSize: 15, lineHeight: 22 },
  muted: { ...typeface.regular, color: t.text, fontSize: 14, lineHeight: 21 },
  summaryCard: { width: "100%", maxWidth: 560, alignSelf: "center", paddingHorizontal: spacing.lg, paddingTop: spacing.xs,
    borderWidth: 1, borderColor: t.cardBdr, borderRadius: radii.card, backgroundColor: t.cardBg, ...t.cardShadow },
  receiptCard: { width: "100%", maxWidth: 560, alignSelf: "center", marginTop: spacing.sm, paddingHorizontal: spacing.lg, paddingTop: spacing.xs,
    borderWidth: 1, borderColor: t.cardBdr, borderRadius: radii.card, backgroundColor: t.cardBg, ...t.cardShadow },
  summaryRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, paddingVertical: spacing.md },
  rowBorder: { borderTopWidth: 1, borderTopColor: t.divider },
  rowLabel: { ...typeface.regular, flex: 1, color: t.text, fontSize: 15, lineHeight: 22 },
  rowValue: { ...typeface.semibold, flex: 1, color: t.strong, fontSize: 16, lineHeight: 22, textAlign: "right" },
  totalRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, paddingTop: spacing.lg, paddingBottom: spacing.md },
  totalLabel: { ...typeface.semibold, color: t.strong, fontSize: 17,},
  creating: { minHeight: 300, alignItems: "center", justifyContent: "center", gap: spacing.lg },
  creatingLogo: { width: 84, height: 84, borderRadius: 18 },
  creatingText: { ...typeface.semibold, color: t.strong, fontSize: 16,},
  amount: { ...typeface.bold, color: t.strong, fontSize: 24,},
  confirmation: { alignItems: "center", gap: spacing.md, paddingVertical: spacing.xl },
  confirmationTitle: { ...typeface.bold, color: t.strong, fontSize: 24, textAlign: "center" },
  reference: { ...typeface.semibold, flex: 1, color: t.strong, fontSize: 15, letterSpacing: 0.6, textAlign: "right" },
  paymentState: { ...typeface.regular, color: t.text, fontSize: 14, lineHeight: 21, paddingBottom: spacing.md },
  signature: { width: "100%", aspectRatio: 2, borderRadius: 8 },
  actionBar: { borderTopWidth: 0, backgroundColor: "transparent", paddingTop: spacing.md, gap: spacing.sm },
  secondaryActions: { flexDirection: "row", gap: spacing.sm },
  secondaryAction: { flex: 1 },
})
